//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_342.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentDetail()
        {
            this.StudentTeacherDetails = new HashSet<StudentTeacherDetail>();
        }
    
        public long Id { get; set; }
        public string Fname { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public long Country { get; set; }
        public long State { get; set; }
        public long City { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string TeacherId { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual State State1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTeacherDetail> StudentTeacherDetails { get; set; }
    }
}
